add installer

diff --git a/etc/install b/etc/install
--- a/etc/install
+++ b/etc/install
@@ -147,4 +147,37 @@ else
   log_info "Exist."
 fi
 
+log_info "Run Ansible Playbook"
+sh $HOME/work/my-setup-fedora/run install
+if [ $? -ne 0 ]; then
+  log_suc "Success."
+else
+  log_err "Failed to install. Exit script."
+  exit 1
+fi
+
+# copy dotfiles
+DOTFILE_DIR=$HOME/dotfiles
+CONFIG_DIR=$HOME/.config
+
+ln -sf $DOTFILE_DIR/.Xresources $HOME/.Xresources
+ln -sf $DOTFILE_DIR/.bashrc $HOME/.bashrc
+ln -sf $DOTFILE_DIR/.bash_profile $HOME/.bash_profile
+ln -sf $DOTFILE_DIR/.fzf.bash $HOME/.fzf.bash
+ln -sf $DOTFILE_DIR/.gitconfig $HOME/.gitconfig
+ln -sf $DOTFILE_DIR/.tmux.conf $HOME/.tmux.conf
+ln -sf $DOTFILE_DIR/.vim $HOME/.vim
+ln -sf $DOTFILE_DIR/.vimrc $HOME/.vimrc
+ln -sf $DOTFILE_DIR/config/gtk/.gtkrc-2.0 $HOME/.gtkrc-2.0
+
+ln -sf $DOTFILE_DIR/config/i3 $CONFIG_DIR/i3
+ln -sf $DOTFILE_DIR/config/nitrogen $CONFIG_DIR/nitrogen
+ln -sf $DOTFILE_DIR/config/polybar $CONFIG_DIR/polybar
+ln -sf $DOTFILE_DIR/config/ranger $CONFIG_DIR/ranger
+ln -sf $DOTFILE_DIR/config/rofi $CONFIG_DIR/rofi
+ln -sf $DOTFILE_DIR/config/gtk/settings.ini $CONFIG_DIR/gtk-3.0/settings.ini
+ln -sf $DOTFILE_DIR/config/betterlockscreen/betterlockscreenrc $CONFIG_DIR/betterlockscreenrc
+
+ln -s $DOTFILE_DIR/bin $HOME/.local/bin
+
 log_info "Done."
